/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ManageNodeImport } from './routes/manage-node'
import { Route as ManageKeyImport } from './routes/manage-key'
import { Route as IndexImport } from './routes/index'
import { Route as ManageApiIndexImport } from './routes/manage-api/index'

// Create/Update Routes

const ManageNodeRoute = ManageNodeImport.update({
  path: '/manage-node',
  getParentRoute: () => rootRoute,
} as any)

const ManageKeyRoute = ManageKeyImport.update({
  path: '/manage-key',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ManageApiIndexRoute = ManageApiIndexImport.update({
  path: '/manage-api/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/manage-key': {
      id: '/manage-key'
      path: '/manage-key'
      fullPath: '/manage-key'
      preLoaderRoute: typeof ManageKeyImport
      parentRoute: typeof rootRoute
    }
    '/manage-node': {
      id: '/manage-node'
      path: '/manage-node'
      fullPath: '/manage-node'
      preLoaderRoute: typeof ManageNodeImport
      parentRoute: typeof rootRoute
    }
    '/manage-api/': {
      id: '/manage-api/'
      path: '/manage-api'
      fullPath: '/manage-api'
      preLoaderRoute: typeof ManageApiIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ManageKeyRoute,
  ManageNodeRoute,
  ManageApiIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/manage-key",
        "/manage-node",
        "/manage-api/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/manage-key": {
      "filePath": "manage-key.tsx"
    },
    "/manage-node": {
      "filePath": "manage-node.tsx"
    },
    "/manage-api/": {
      "filePath": "manage-api/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
