/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ManageApiImport } from './routes/manage-api'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ManageApiRoute = ManageApiImport.update({
  path: '/manage-api',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/manage-api': {
      id: '/manage-api'
      path: '/manage-api'
      fullPath: '/manage-api'
      preLoaderRoute: typeof ManageApiImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ IndexRoute, ManageApiRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/manage-api"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/manage-api": {
      "filePath": "manage-api.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
